[build]
  functions = "netlify/functions"
  publish = "build" # or "dist", "public", or "." depending on your frontend output folder

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
  force = false