[build]
  command = "npm install && npm run build:web"
  functions = "netlify/functions"
  publish = "dist" # Expo exports to "dist" directory, not "build"

[dev]
  framework = "#custom"
  command = "npx expo start --web --port 19006"
  port = 8082
  targetPort = 19006
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Allow auth routes to pass through to your app (important for Supabase password reset)
[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200

# Catch everything else
[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
  force = false
