[build]
  # functions = "netlify/functions"  # Temporarily disabled for deployment
  publish = "build" # or "dist", "public", or "." depending on your frontend output folder

# Temporarily disabled for deployment
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
  force = false